name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build
      run: make build
    - name: Lint
      run: make lint
    - name: Format Check
      run: make fmt-check
    - name: Run tests
      run: make test
    - name: Run shell tests
      run: make test-cmd
    - name: Run integration pose → docker → network tests
      run: make test-integration
    - name: Run shell integration pose → docker → network tests
      run: make test-cmd-integration
