name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Format Check
      run: cargo fmt -- --check
    - name: Run tests
      run: cargo test
    - name: Run --help
      run: cargo run -- --help
